## Structuring data with Python.

**The Python code below standardizes and normalizes housing data.**


* **Click the double right-arrow icon to restart the kernel and run all cells.**
* **Add statements that display the original, standardized, and normalized data.**
* **Verify that the original, standardized, and normalized data is the same as in the feature scaling animation above.**

In [1]:
# Import packages
import pandas as pd
from sklearn import preprocessing

# Import data into 'original'
original = pd.read_csv('featurescaling.csv')

original

   Price  Age
0  10000   10
1  20000   20
2  30000   30
3  40000   40
4  50000   50

In [2]:
# Standardize dataframe and return as an array
standardizedArray = preprocessing.scale(original)

# Convert standardized array to dataframe 'standardized'
standardized = pd.DataFrame(standardizedArray, columns=["Price", "Age"])

In [3]:
# Verify that standardized contains the expected values
standardized

      Price       Age
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

In [4]:
# Normalize dataframe and return as an array
normalizedArray = preprocessing.MinMaxScaler().fit_transform(original)

# Convert normalized array to dataframe 'normalized'
normalized = pd.DataFrame(normalizedArray, columns=["Price", "Age"])

In [5]:
# Verify that normalized contains the expected values
normalized

   Price   Age
0   0.00  0.00
1   0.25  0.25
2   0.50  0.50
3   0.75  0.75
4   1.00  1.00

## CHALLENGE ACTIVITY| 5.3.2: Structuring data using scikit-learn.

## 1) 
**This dataset contains information on credit card customers, such as the customer's average credit limit, number of credit cards, number of physical visits to the bank, and number of visits to the bank's website.**

* **Standardize the data for the features Avg_Credit_Limit and Total_visits_online.**
  
**The code contains all imports, loads the dataset, subsets the data, and displays five lines of the standardized data.**

In [ ]:


# Load the dataset
df = pd.read_csv('credit_card.csv')

# Create a new dataframe with two features
dfCredit = df[['Avg_Credit_Limit', 'Total_visits_online']]

# Standardize dataframe and return as an array
standardizedArray = # Your code goes here

# Convert standardized array to dataframe
dfCreditStandardized = pd.DataFrame(standardizedArray, columns=['Avg_Credit_Limit', 'Total_visits_online'])

# Print five lines of the standardized data
print(dfCreditStandardized[511:516])

## 2)
**This dataset contains information on credit card customers, such as the customer's average credit limit, number of credit cards, number of physical visits to the bank, and number of visits to the bank's website.**

* **Normalize the data for the features Avg_Credit_Limit and Total_visits_online.**

  
**The code contains all imports, loads the dataset, subsets the data, and displays five lines of the normalized data.**

In [ ]:


# Create a new dataframe with two features
ccOriginal = df[['Avg_Credit_Limit', 'Total_visits_online']]

# Normalize dataframe and return as an array
normalizedArray = # Your code goes here

# Convert normalized array to dataframe
ccOriginalNormalized = pd.DataFrame(normalizedArray, columns=['Avg_Credit_Limit', 'Total_visits_online'])

# Print five lines of the normalized data
print(ccOriginalNormalized[591:596])